# Generated by Django 5.2.7 on 2025-10-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('kind', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('ref', models.CharField(blank=True, max_length=64, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('side', models.CharField(max_length=4)),
                ('lots', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('type', models.CharField(default='market', max_length=16)),
                ('status', models.CharField(default='filled', max_length=16)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('net_lots', models.DecimalField(decimal_places=6, max_digits=20)),
                ('avg_entry', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unreal_pnl', models.DecimalField(decimal_places=8, max_digits=28)),
                ('margin', models.DecimalField(decimal_places=8, max_digits=28)),
                ('mark', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('side', models.CharField(max_length=4)),
                ('lots', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='marketdata.order')),
            ],
        ),
    ]
