# Generated by Django 5.2.7 on 2025-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
