# Generated by Django 5.2.7 on 2025-10-30 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_order_position_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('users', models.ManyToManyField(related_name='trade_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminBroadcastTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=40, unique=True)),
                ('symbol', models.CharField(max_length=24)),
                ('side', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('lots', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_to_user_ids', models.JSONField(blank=True, default=list)),
                ('groups', models.ManyToManyField(blank=True, related_name='trades', to='marketdata.usertradegroup')),
            ],
        ),
        migrations.CreateModel(
            name='AdminTradeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realized', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='marketdata.adminbroadcasttrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trade', 'user')},
            },
        ),
    ]
