# Generated by Django 5.2.7 on 2025-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_usertradegroup_adminbroadcasttrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbroadcasttrade',
            name='leverage',
            field=models.IntegerField(default=500),
        ),
    ]
