# Generated by Django 5.2.7 on 2025-10-30 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_adminbroadcasttrade_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbroadcasttrade',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
