# Generated by Django 5.2.7 on 2025-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0009_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlltickConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Your Alltick API Key', max_length=255)),
                ('base_rest_url', models.URLField(default='https://quote.tradeswitch.net/quote-b-api', help_text='REST API Endpoint')),
                ('base_ws_url', models.URLField(default='wss://quote.tradeswitch.net/quote-b-ws-api', help_text='WebSocket Endpoint')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alltick Configuration',
                'verbose_name_plural': 'Alltick Configuration',
                'ordering': ['-updated_at'],
            },
        ),
    ]
