# Generated by Django 5.2.7 on 2025-12-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0010_alltickconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltickconfig',
            name='base_ws_url',
            field=models.CharField(default='wss://quote.tradeswitch.net/quote-b-ws-api', help_text='WebSocket Endpoint'),
        ),
    ]
