# Generated by Django 5.2.7 on 2025-11-02 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDepositMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='USDT', max_length=32)),
                ('network', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('min_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=16)),
                ('qr_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'network'],
                'unique_together': {('name', 'network', 'address')},
            },
        ),
        migrations.CreateModel(
            name='UpiDepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payer_vpa', models.CharField(help_text="User's UPI ID (VPA)", max_length=120)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved / Credited'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utr', models.CharField(blank=True, max_length=64)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
